blueprint:
  title: Harnessing the Power of Natural Science Collections
  description: |
    DiSSCo UK is harnessing the full potential of the UK's natural science collections
    by making them physically and digitally open, accessible, and usable for all forms
    of research and innovation. The DiSSCo UK Blueprint describes how the consortium
    aims to scale up digitisation and cooperation through a national infrastructure
    programme.
  background: /assets/images/dissco_map.png
  cta:
    - text: Download report
      href: /assets/Harnessing the Power of Natural Science Collections.pdf
      isPrimary: true

latest:
  title: Latest news

main:
  klass: home_main
  markdownContent: |
    # this is just a copy of the GBIF heroImage block but with an added spacer and video
    <div class="feature-img">
        <img src="/assets/images/sample_home.JPG">
        <div class="feature-img-license">
            <div class="feature-img-license-c">
              <span class="icon"><i class="fa fa-info-circle"></i></span>
            </div>
            <div class="feature-img-license-text">
                <p>Copyright Trustees of the Natural History Museum</p>
            </div>
        </div>
    </div>
    <div class="feature-content ">
        <div class="feature-text">
            <h3 class="feature-title">
                <p>The Distributed System of Scientific Collections</p>
            </h3>
        </div>
        <div class="spacer"></div>
        <iframe src="https://www.youtube.com/embed/4Ad1SCl0s6w" title="Harnessing the Power of Natural Science Collections" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
        </iframe>
        <div class="feature-cta">
          <a href="/specimen/search" class="button is-primary">Explore specimens</a>
          <a href="/institution/search" class="button">Explore institutions</a>
        </div>
    </div>
